//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:32:21 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.ejbjar.jeus.v5_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for passwordTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="passwordTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PasswordDigest"/>
 *     &lt;enumeration value="PasswordText"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "passwordTypeType")
@XmlEnum
public enum PasswordTypeType {


    /**
     * 
     * 						[Description]: UsernameToken에 설정되는 암호가 Base64 ( SHA-1 ( nonce + created + password ) ) -> base64 encoding된 상태로 메시지에 포함된다.
     * 					
     * 
     */
    @XmlEnumValue("PasswordDigest")
    PASSWORD_DIGEST("PasswordDigest"),

    /**
     * 
     * 						[Description]: UsernameToken에 설정되는 암호가 평문으로 메시지에 포함된다.
     * 					
     * 
     */
    @XmlEnumValue("PasswordText")
    PASSWORD_TEXT("PasswordText");
    private final String value;

    PasswordTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PasswordTypeType fromValue(String v) {
        for (PasswordTypeType c: PasswordTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
