//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:32:21 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.ejbjar.jeus.v5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for persistence-optimizeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="persistence-optimizeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="engine-type" type="{http://www.tmaxsoft.com/xml/ns/jeus}engineType" minOccurs="0"/>
 *         &lt;element name="non-modifying-method" type="{http://www.tmaxsoft.com/xml/ns/jeus}methodParamType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="entity-cache-size" type="{http://www.tmaxsoft.com/xml/ns/jeus}nonNegativeIntType" minOccurs="0"/>
 *         &lt;element name="update-delay-till-tx" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="include-update" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "persistence-optimizeType", propOrder = {
    "engineType",
    "nonModifyingMethod",
    "entityCacheSize",
    "updateDelayTillTx",
    "includeUpdate"
})
public class PersistenceOptimizeType {

    @XmlElement(name = "engine-type", defaultValue = "EXCLUSIVE_ACCESS")
    protected EngineType engineType;
    @XmlElement(name = "non-modifying-method")
    protected List<MethodParamType> nonModifyingMethod;
    @XmlElement(name = "entity-cache-size", defaultValue = "2000")
    protected Integer entityCacheSize;
    @XmlElement(name = "update-delay-till-tx", defaultValue = "true")
    protected Boolean updateDelayTillTx;
    @XmlElement(name = "include-update", defaultValue = "false")
    protected Boolean includeUpdate;

    /**
     * Gets the value of the engineType property.
     * 
     * @return
     *     possible object is
     *     {@link EngineType }
     *     
     */
    public EngineType getEngineType() {
        return engineType;
    }

    /**
     * Sets the value of the engineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EngineType }
     *     
     */
    public void setEngineType(EngineType value) {
        this.engineType = value;
    }

    /**
     * Gets the value of the nonModifyingMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonModifyingMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonModifyingMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MethodParamType }
     * 
     * 
     */
    public List<MethodParamType> getNonModifyingMethod() {
        if (nonModifyingMethod == null) {
            nonModifyingMethod = new ArrayList<MethodParamType>();
        }
        return this.nonModifyingMethod;
    }

    /**
     * Gets the value of the entityCacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEntityCacheSize() {
        return entityCacheSize;
    }

    /**
     * Sets the value of the entityCacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEntityCacheSize(Integer value) {
        this.entityCacheSize = value;
    }

    /**
     * Gets the value of the updateDelayTillTx property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateDelayTillTx() {
        return updateDelayTillTx;
    }

    /**
     * Sets the value of the updateDelayTillTx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateDelayTillTx(Boolean value) {
        this.updateDelayTillTx = value;
    }

    /**
     * Gets the value of the includeUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeUpdate() {
        return includeUpdate;
    }

    /**
     * Sets the value of the includeUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeUpdate(Boolean value) {
        this.includeUpdate = value;
    }

}
