//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 07:02:27 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v6_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for canonicalizationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="canonicalizationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="http://www.w3.org/2001/10/xml-exc-c14n#"/>
 *     &lt;enumeration value="http://www.w3.org/2001/10/xml-exc-c14n#WithComments"/>
 *     &lt;enumeration value="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
 *     &lt;enumeration value="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum CanonicalizationType {

    @XmlEnumValue("http://www.w3.org/2001/10/xml-exc-c14n#")
    HTTP_WWW_W_3_ORG_2001_10_XML_EXC_C_14_N("http://www.w3.org/2001/10/xml-exc-c14n#"),
    @XmlEnumValue("http://www.w3.org/2001/10/xml-exc-c14n#WithComments")
    HTTP_WWW_W_3_ORG_2001_10_XML_EXC_C_14_N_WITH_COMMENTS("http://www.w3.org/2001/10/xml-exc-c14n#WithComments"),
    @XmlEnumValue("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")
    HTTP_WWW_W_3_ORG_TR_2001_REC_XML_C_14_N_20010315("http://www.w3.org/TR/2001/REC-xml-c14n-20010315"),
    @XmlEnumValue("http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments")
    HTTP_WWW_W_3_ORG_TR_2001_REC_XML_C_14_N_20010315_WITH_COMMENTS("http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments");
    private final String value;

    CanonicalizationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CanonicalizationType fromValue(String v) {
        for (CanonicalizationType c: CanonicalizationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
