//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 07:02:27 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v6_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ejb-componentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ejb-componentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="deployment-target" type="{http://www.tmaxsoft.com/xml/ns/jeus}deployment-targetType" minOccurs="0"/>
 *         &lt;element name="client-view-path" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="keep-generated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ejb-jar" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="jeus-ejb-dd" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="java-security-permission" type="{http://www.tmaxsoft.com/xml/ns/jeus}securityPermissionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ejb-componentType", propOrder = {
    "uri",
    "deploymentTarget",
    "clientViewPath",
    "keepGenerated",
    "ejbJar",
    "jeusEjbDd",
    "javaSecurityPermission"
})
public class EjbComponentType {

    @XmlElement(namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String uri;
    @XmlElement(name = "deployment-target", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected DeploymentTargetType deploymentTarget;
    @XmlElement(name = "client-view-path", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String clientViewPath;
    @XmlElement(name = "keep-generated", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected Boolean keepGenerated;
    @XmlElement(name = "ejb-jar", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ejbJar;
    @XmlElement(name = "jeus-ejb-dd", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jeusEjbDd;
    @XmlElement(name = "java-security-permission", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected SecurityPermissionType javaSecurityPermission;

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the deploymentTarget property.
     * 
     * @return
     *     possible object is
     *     {@link DeploymentTargetType }
     *     
     */
    public DeploymentTargetType getDeploymentTarget() {
        return deploymentTarget;
    }

    /**
     * Sets the value of the deploymentTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeploymentTargetType }
     *     
     */
    public void setDeploymentTarget(DeploymentTargetType value) {
        this.deploymentTarget = value;
    }

    /**
     * Gets the value of the clientViewPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientViewPath() {
        return clientViewPath;
    }

    /**
     * Sets the value of the clientViewPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientViewPath(String value) {
        this.clientViewPath = value;
    }

    /**
     * Gets the value of the keepGenerated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeepGenerated() {
        return keepGenerated;
    }

    /**
     * Sets the value of the keepGenerated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeepGenerated(Boolean value) {
        this.keepGenerated = value;
    }

    /**
     * Gets the value of the ejbJar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjbJar() {
        return ejbJar;
    }

    /**
     * Sets the value of the ejbJar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjbJar(String value) {
        this.ejbJar = value;
    }

    /**
     * Gets the value of the jeusEjbDd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJeusEjbDd() {
        return jeusEjbDd;
    }

    /**
     * Sets the value of the jeusEjbDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJeusEjbDd(String value) {
        this.jeusEjbDd = value;
    }

    /**
     * Gets the value of the javaSecurityPermission property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityPermissionType }
     *     
     */
    public SecurityPermissionType getJavaSecurityPermission() {
        return javaSecurityPermission;
    }

    /**
     * Sets the value of the javaSecurityPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityPermissionType }
     *     
     */
    public void setJavaSecurityPermission(SecurityPermissionType value) {
        this.javaSecurityPermission = value;
    }

}
