//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 07:02:27 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v6_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data-source" type="{http://www.tmaxsoft.com/xml/ns/jeus}data-sourceType" minOccurs="0"/>
 *         &lt;element name="mail-source" type="{http://www.tmaxsoft.com/xml/ns/jeus}mail-sourceType" minOccurs="0"/>
 *         &lt;element name="url-source" type="{http://www.tmaxsoft.com/xml/ns/jeus}url-sourceType" minOccurs="0"/>
 *         &lt;element name="message-bridge" type="{http://www.tmaxsoft.com/xml/ns/jeus}message-bridgeType" minOccurs="0"/>
 *         &lt;element name="external-source" type="{http://www.tmaxsoft.com/xml/ns/jeus}external-sourceType" minOccurs="0"/>
 *         &lt;element name="external-resource" type="{http://www.tmaxsoft.com/xml/ns/jeus}external-resourceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="jaxr-source" type="{http://www.tmaxsoft.com/xml/ns/jeus}jaxr-sourceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceType", propOrder = {
    "dataSource",
    "mailSource",
    "urlSource",
    "messageBridge",
    "externalSource",
    "externalResource",
    "jaxrSource"
})
public class ResourceType {

    @XmlElement(name = "data-source", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected DataSourceType dataSource;
    @XmlElement(name = "mail-source", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected MailSourceType mailSource;
    @XmlElement(name = "url-source", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected UrlSourceType urlSource;
    @XmlElement(name = "message-bridge", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected MessageBridgeType messageBridge;
    @XmlElement(name = "external-source", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected ExternalSourceType externalSource;
    @XmlElement(name = "external-resource", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", required = true)
    protected List<ExternalResourceType> externalResource;
    @XmlElement(name = "jaxr-source", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected JaxrSourceType jaxrSource;

    /**
     * Gets the value of the dataSource property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourceType }
     *     
     */
    public DataSourceType getDataSource() {
        return dataSource;
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourceType }
     *     
     */
    public void setDataSource(DataSourceType value) {
        this.dataSource = value;
    }

    /**
     * Gets the value of the mailSource property.
     * 
     * @return
     *     possible object is
     *     {@link MailSourceType }
     *     
     */
    public MailSourceType getMailSource() {
        return mailSource;
    }

    /**
     * Sets the value of the mailSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailSourceType }
     *     
     */
    public void setMailSource(MailSourceType value) {
        this.mailSource = value;
    }

    /**
     * Gets the value of the urlSource property.
     * 
     * @return
     *     possible object is
     *     {@link UrlSourceType }
     *     
     */
    public UrlSourceType getUrlSource() {
        return urlSource;
    }

    /**
     * Sets the value of the urlSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrlSourceType }
     *     
     */
    public void setUrlSource(UrlSourceType value) {
        this.urlSource = value;
    }

    /**
     * Gets the value of the messageBridge property.
     * 
     * @return
     *     possible object is
     *     {@link MessageBridgeType }
     *     
     */
    public MessageBridgeType getMessageBridge() {
        return messageBridge;
    }

    /**
     * Sets the value of the messageBridge property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageBridgeType }
     *     
     */
    public void setMessageBridge(MessageBridgeType value) {
        this.messageBridge = value;
    }

    /**
     * Gets the value of the externalSource property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalSourceType }
     *     
     */
    public ExternalSourceType getExternalSource() {
        return externalSource;
    }

    /**
     * Sets the value of the externalSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalSourceType }
     *     
     */
    public void setExternalSource(ExternalSourceType value) {
        this.externalSource = value;
    }

    /**
     * Gets the value of the externalResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalResourceType }
     * 
     * 
     */
    public List<ExternalResourceType> getExternalResource() {
        if (externalResource == null) {
            externalResource = new ArrayList<ExternalResourceType>();
        }
        return this.externalResource;
    }

    /**
     * Gets the value of the jaxrSource property.
     * 
     * @return
     *     possible object is
     *     {@link JaxrSourceType }
     *     
     */
    public JaxrSourceType getJaxrSource() {
        return jaxrSource;
    }

    /**
     * Sets the value of the jaxrSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxrSourceType }
     *     
     */
    public void setJaxrSource(JaxrSourceType value) {
        this.jaxrSource = value;
    }

}
