//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.05 at 01:53:24 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.weblogic.v9_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entity-mappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entity-mappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entity-mapping-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="public-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="system-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="entity-uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="when-to-cache" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cache-timeout-interval" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entity-mappingType", propOrder = {
    "entityMappingName",
    "publicId",
    "systemId",
    "entityUri",
    "whenToCache",
    "cacheTimeoutInterval"
})
public class EntityMappingType {

    @XmlElement(name = "entity-mapping-name", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected java.lang.String entityMappingName;
    @XmlElement(name = "public-id", namespace = "http://www.bea.com/ns/weblogic/90")
    protected java.lang.String publicId;
    @XmlElement(name = "system-id", namespace = "http://www.bea.com/ns/weblogic/90")
    protected java.lang.String systemId;
    @XmlElement(name = "entity-uri", namespace = "http://www.bea.com/ns/weblogic/90")
    protected java.lang.String entityUri;
    @XmlElement(name = "when-to-cache", namespace = "http://www.bea.com/ns/weblogic/90")
    protected java.lang.String whenToCache;
    @XmlElement(name = "cache-timeout-interval", namespace = "http://www.bea.com/ns/weblogic/90")
    protected Integer cacheTimeoutInterval;

    /**
     * Gets the value of the entityMappingName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEntityMappingName() {
        return entityMappingName;
    }

    /**
     * Sets the value of the entityMappingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEntityMappingName(java.lang.String value) {
        this.entityMappingName = value;
    }

    /**
     * Gets the value of the publicId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPublicId() {
        return publicId;
    }

    /**
     * Sets the value of the publicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPublicId(java.lang.String value) {
        this.publicId = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSystemId(java.lang.String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the entityUri property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEntityUri() {
        return entityUri;
    }

    /**
     * Sets the value of the entityUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEntityUri(java.lang.String value) {
        this.entityUri = value;
    }

    /**
     * Gets the value of the whenToCache property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getWhenToCache() {
        return whenToCache;
    }

    /**
     * Sets the value of the whenToCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setWhenToCache(java.lang.String value) {
        this.whenToCache = value;
    }

    /**
     * Gets the value of the cacheTimeoutInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheTimeoutInterval() {
        return cacheTimeoutInterval;
    }

    /**
     * Sets the value of the cacheTimeoutInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheTimeoutInterval(Integer value) {
        this.cacheTimeoutInterval = value;
    }

}
