//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.05 at 01:53:24 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.weblogic.v9_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for prepared-statementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prepared-statementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="profiling-enabled" type="{http://www.bea.com/ns/weblogic/90}true-falseType" minOccurs="0"/>
 *         &lt;element name="cache-profiling-threshold" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cache-size" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="parameter-logging-enabled" type="{http://www.bea.com/ns/weblogic/90}true-falseType" minOccurs="0"/>
 *         &lt;element name="max-parameter-length" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cache-type" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prepared-statementType", propOrder = {
    "profilingEnabled",
    "cacheProfilingThreshold",
    "cacheSize",
    "parameterLoggingEnabled",
    "maxParameterLength",
    "cacheType"
})
public class PreparedStatementType {

    @XmlElement(name = "profiling-enabled", namespace = "http://www.bea.com/ns/weblogic/90")
    protected TrueFalseType profilingEnabled;
    @XmlElement(name = "cache-profiling-threshold", namespace = "http://www.bea.com/ns/weblogic/90")
    protected Integer cacheProfilingThreshold;
    @XmlElement(name = "cache-size", namespace = "http://www.bea.com/ns/weblogic/90")
    protected Integer cacheSize;
    @XmlElement(name = "parameter-logging-enabled", namespace = "http://www.bea.com/ns/weblogic/90")
    protected TrueFalseType parameterLoggingEnabled;
    @XmlElement(name = "max-parameter-length", namespace = "http://www.bea.com/ns/weblogic/90")
    protected Integer maxParameterLength;
    @XmlElement(name = "cache-type", namespace = "http://www.bea.com/ns/weblogic/90")
    protected Integer cacheType;

    /**
     * Gets the value of the profilingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getProfilingEnabled() {
        return profilingEnabled;
    }

    /**
     * Sets the value of the profilingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setProfilingEnabled(TrueFalseType value) {
        this.profilingEnabled = value;
    }

    /**
     * Gets the value of the cacheProfilingThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheProfilingThreshold() {
        return cacheProfilingThreshold;
    }

    /**
     * Sets the value of the cacheProfilingThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheProfilingThreshold(Integer value) {
        this.cacheProfilingThreshold = value;
    }

    /**
     * Gets the value of the cacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheSize() {
        return cacheSize;
    }

    /**
     * Sets the value of the cacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheSize(Integer value) {
        this.cacheSize = value;
    }

    /**
     * Gets the value of the parameterLoggingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getParameterLoggingEnabled() {
        return parameterLoggingEnabled;
    }

    /**
     * Sets the value of the parameterLoggingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setParameterLoggingEnabled(TrueFalseType value) {
        this.parameterLoggingEnabled = value;
    }

    /**
     * Gets the value of the maxParameterLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxParameterLength() {
        return maxParameterLength;
    }

    /**
     * Sets the value of the maxParameterLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxParameterLength(Integer value) {
        this.maxParameterLength = value;
    }

    /**
     * Gets the value of the cacheType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheType() {
        return cacheType;
    }

    /**
     * Sets the value of the cacheType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheType(Integer value) {
        this.cacheType = value;
    }

}
