//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.12 at 01:39:08 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.weblogic.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ejbType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ejbType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entity-cache" type="{http://www.bea.com/ns/weblogic/weblogic-application}application-entity-cacheType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="start-mdbs-with-application" type="{http://www.bea.com/ns/weblogic/weblogic-application}true-falseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ejbType", namespace = "http://www.bea.com/ns/weblogic/weblogic-application", propOrder = {
    "entityCache",
    "startMdbsWithApplication"
})
public class EjbType {

    @XmlElement(name = "entity-cache", namespace = "http://www.bea.com/ns/weblogic/weblogic-application", required = true)
    protected List<ApplicationEntityCacheType> entityCache;
    @XmlElement(name = "start-mdbs-with-application", namespace = "http://www.bea.com/ns/weblogic/weblogic-application")
    protected TrueFalseType startMdbsWithApplication;

    /**
     * Gets the value of the entityCache property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityCache property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityCache().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationEntityCacheType }
     * 
     * 
     */
    public List<ApplicationEntityCacheType> getEntityCache() {
        if (entityCache == null) {
            entityCache = new ArrayList<ApplicationEntityCacheType>();
        }
        return this.entityCache;
    }

    /**
     * Gets the value of the startMdbsWithApplication property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getStartMdbsWithApplication() {
        return startMdbsWithApplication;
    }

    /**
     * Sets the value of the startMdbsWithApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setStartMdbsWithApplication(TrueFalseType value) {
        this.startMdbsWithApplication = value;
    }

}
