//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.12 at 01:39:08 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.weblogic.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;


/**
 * <p>Java class for xmlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parser-factory" type="{http://www.bea.com/ns/weblogic/weblogic-application}parser-factoryType" minOccurs="0"/>
 *         &lt;element name="entity-mapping" type="{http://www.bea.com/ns/weblogic/weblogic-application}entity-mappingType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@javax.xml.bind.annotation.XmlType(name = "xmlType", namespace = "http://www.bea.com/ns/weblogic/weblogic-application", propOrder = {
    "parserFactory",
    "entityMapping"
})
public class XmlType {

    @XmlElement(name = "parser-factory", namespace = "http://www.bea.com/ns/weblogic/weblogic-application")
    protected ParserFactoryType parserFactory;
    @XmlElement(name = "entity-mapping", namespace = "http://www.bea.com/ns/weblogic/weblogic-application", required = true)
    protected List<EntityMappingType> entityMapping;

    /**
     * Gets the value of the parserFactory property.
     * 
     * @return
     *     possible object is
     *     {@link ParserFactoryType }
     *     
     */
    public ParserFactoryType getParserFactory() {
        return parserFactory;
    }

    /**
     * Sets the value of the parserFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParserFactoryType }
     *     
     */
    public void setParserFactory(ParserFactoryType value) {
        this.parserFactory = value;
    }

    /**
     * Gets the value of the entityMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityMappingType }
     * 
     * 
     */
    public List<EntityMappingType> getEntityMapping() {
        if (entityMapping == null) {
            entityMapping = new ArrayList<EntityMappingType>();
        }
        return this.entityMapping;
    }

}
