//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.06 at 09:23:00 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.weblogicejbjar.v9_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for iiop-security-descriptorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="iiop-security-descriptorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transport-requirements" type="{http://www.bea.com/ns/weblogic/90}transport-requirementsType" minOccurs="0"/>
 *         &lt;element name="client-authentication" type="{http://www.bea.com/ns/weblogic/90}client-authenticationType" minOccurs="0"/>
 *         &lt;element name="identity-assertion" type="{http://www.bea.com/ns/weblogic/90}identity-assertionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iiop-security-descriptorType", propOrder = {
    "transportRequirements",
    "clientAuthentication",
    "identityAssertion"
})
public class IiopSecurityDescriptorType {

    @XmlElement(name = "transport-requirements", namespace = "http://www.bea.com/ns/weblogic/90")
    protected TransportRequirementsType transportRequirements;
    @XmlElement(name = "client-authentication", namespace = "http://www.bea.com/ns/weblogic/90")
    protected ClientAuthenticationType clientAuthentication;
    @XmlElement(name = "identity-assertion", namespace = "http://www.bea.com/ns/weblogic/90")
    protected IdentityAssertionType identityAssertion;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected java.lang.String id;

    /**
     * Gets the value of the transportRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link TransportRequirementsType }
     *     
     */
    public TransportRequirementsType getTransportRequirements() {
        return transportRequirements;
    }

    /**
     * Sets the value of the transportRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportRequirementsType }
     *     
     */
    public void setTransportRequirements(TransportRequirementsType value) {
        this.transportRequirements = value;
    }

    /**
     * Gets the value of the clientAuthentication property.
     * 
     * @return
     *     possible object is
     *     {@link ClientAuthenticationType }
     *     
     */
    public ClientAuthenticationType getClientAuthentication() {
        return clientAuthentication;
    }

    /**
     * Sets the value of the clientAuthentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientAuthenticationType }
     *     
     */
    public void setClientAuthentication(ClientAuthenticationType value) {
        this.clientAuthentication = value;
    }

    /**
     * Gets the value of the identityAssertion property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityAssertionType }
     *     
     */
    public IdentityAssertionType getIdentityAssertion() {
        return identityAssertion;
    }

    /**
     * Sets the value of the identityAssertion property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityAssertionType }
     *     
     */
    public void setIdentityAssertion(IdentityAssertionType value) {
        this.identityAssertion = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
