//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:32:21 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.jeusejbdd.v5_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for encryptionAlgorithmType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="encryptionAlgorithmType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#tripledes-cbc"/>
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#aes192-cbc"/>
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
 *     &lt;enumeration value="http://www.tmaxsoft.com/xml/algorithms/xmlenc#seed-cbc"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "encryptionAlgorithmType")
@XmlEnum
public enum EncryptionAlgorithmType {


    /**
     * 
     * 						[Description]: DESEDE-CBC
     * 					
     * 
     */
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#tripledes-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_TRIPLEDES_CBC("http://www.w3.org/2001/04/xmlenc#tripledes-cbc"),

    /**
     * 
     * 						[Description]: AES128-CBC
     * 					
     * 
     */
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#aes128-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_AES_128_CBC("http://www.w3.org/2001/04/xmlenc#aes128-cbc"),

    /**
     * 
     * 						[Description]: AES192-CBC
     * 					
     * 
     */
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#aes192-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_AES_192_CBC("http://www.w3.org/2001/04/xmlenc#aes192-cbc"),

    /**
     * 
     * 						[Description]: AES256-CBC
     * 					
     * 
     */
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#aes256-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_AES_256_CBC("http://www.w3.org/2001/04/xmlenc#aes256-cbc"),

    /**
     * 
     * 						[Description]: SEED-CBC
     * 					
     * 
     */
    @XmlEnumValue("http://www.tmaxsoft.com/xml/algorithms/xmlenc#seed-cbc")
    HTTP_WWW_TMAXSOFT_COM_XML_ALGORITHMS_XMLENC_SEED_CBC("http://www.tmaxsoft.com/xml/algorithms/xmlenc#seed-cbc");
    private final String value;

    EncryptionAlgorithmType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EncryptionAlgorithmType fromValue(String v) {
        for (EncryptionAlgorithmType c: EncryptionAlgorithmType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
