//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:32:21 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.jeusejbdd.v5_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for generator-typeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="generator-typeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ORACLE"/>
 *     &lt;enumeration value="MSSQL"/>
 *     &lt;enumeration value="USER_KEY_TABLE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "generator-typeType")
@XmlEnum
public enum GeneratorTypeType {


    /**
     * 
     *                         [Description]: Oracle DB인 경우
     *                     
     * 
     */
    ORACLE,

    /**
     * 
     *                         [Description]: MS SQL DB 인 경우
     *                     
     * 
     */
    MSSQL,

    /**
     * 
     *                         [Description]: Oracle과 MSSQL을 제외한 다른 DB인 경우
     *                     
     * 
     */
    USER_KEY_TABLE;

    public String value() {
        return name();
    }

    public static GeneratorTypeType fromValue(String v) {
        return valueOf(v);
    }

}
