//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 10:14:54 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.ejbjar.jeus.v6_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for encryptionAlgorithmType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="encryptionAlgorithmType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#tripledes-cbc"/>
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#aes192-cbc"/>
 *     &lt;enumeration value="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
 *     &lt;enumeration value="http://www.tmaxsoft.com/xml/algorithms/xmlenc#seed-cbc"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum EncryptionAlgorithmType {

    @XmlEnumValue("http://www.tmaxsoft.com/xml/algorithms/xmlenc#seed-cbc")
    HTTP_WWW_TMAXSOFT_COM_XML_ALGORITHMS_XMLENC_SEED_CBC("http://www.tmaxsoft.com/xml/algorithms/xmlenc#seed-cbc"),
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#aes128-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_AES_128_CBC("http://www.w3.org/2001/04/xmlenc#aes128-cbc"),
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#aes192-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_AES_192_CBC("http://www.w3.org/2001/04/xmlenc#aes192-cbc"),
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#aes256-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_AES_256_CBC("http://www.w3.org/2001/04/xmlenc#aes256-cbc"),
    @XmlEnumValue("http://www.w3.org/2001/04/xmlenc#tripledes-cbc")
    HTTP_WWW_W_3_ORG_2001_04_XMLENC_TRIPLEDES_CBC("http://www.w3.org/2001/04/xmlenc#tripledes-cbc");
    private final String value;

    EncryptionAlgorithmType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EncryptionAlgorithmType fromValue(String v) {
        for (EncryptionAlgorithmType c: EncryptionAlgorithmType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
