//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 10:14:54 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.ejbjar.jeus.v6_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for subengine-typeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="subengine-typeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ReadLocking"/>
 *     &lt;enumeration value="WriteLocking"/>
 *     &lt;enumeration value="WriteLockingFind"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum SubengineTypeType {

    @XmlEnumValue("ReadLocking")
    READ_LOCKING("ReadLocking"),
    @XmlEnumValue("WriteLocking")
    WRITE_LOCKING("WriteLocking"),
    @XmlEnumValue("WriteLockingFind")
    WRITE_LOCKING_FIND("WriteLockingFind");
    private final String value;

    SubengineTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubengineTypeType fromValue(String v) {
        for (SubengineTypeType c: SubengineTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
