//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 02:39:44 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for backup-session-routerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="backup-session-routerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="node-name" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="servlet-engine-name" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="container-base-port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "backup-session-routerType", propOrder = {
    "nodeName",
    "servletEngineName",
    "containerBasePort"
})
public class BackupSessionRouterType {

    @XmlElement(name = "node-name", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nodeName;
    @XmlElement(name = "servlet-engine-name", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String servletEngineName;
    @XmlElement(name = "container-base-port", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "0")
    protected Integer containerBasePort;

    /**
     * Gets the value of the nodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * Sets the value of the nodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeName(String value) {
        this.nodeName = value;
    }

    /**
     * Gets the value of the servletEngineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServletEngineName() {
        return servletEngineName;
    }

    /**
     * Sets the value of the servletEngineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServletEngineName(String value) {
        this.servletEngineName = value;
    }

    /**
     * Gets the value of the containerBasePort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getContainerBasePort() {
        return containerBasePort;
    }

    /**
     * Sets the value of the containerBasePort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setContainerBasePort(Integer value) {
        this.containerBasePort = value;
    }

}
