//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 02:39:44 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v5_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for data-source-typeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="data-source-typeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="DataSource"/>
 *     &lt;enumeration value="ConnectionPoolDataSource"/>
 *     &lt;enumeration value="LocalXADataSource"/>
 *     &lt;enumeration value="XADataSource"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum DataSourceTypeType {

    @XmlEnumValue("ConnectionPoolDataSource")
    CONNECTION_POOL_DATA_SOURCE("ConnectionPoolDataSource"),
    @XmlEnumValue("DataSource")
    DATA_SOURCE("DataSource"),
    @XmlEnumValue("LocalXADataSource")
    LOCAL_XA_DATA_SOURCE("LocalXADataSource"),
    @XmlEnumValue("XADataSource")
    XA_DATA_SOURCE("XADataSource");
    private final String value;

    DataSourceTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataSourceTypeType fromValue(String v) {
        for (DataSourceTypeType c: DataSourceTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
