//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 02:39:44 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for default-credential-mapping-serviceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="default-credential-mapping-serviceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="x509-credential-mapping" type="{http://www.tmaxsoft.com/xml/ns/jeus}x509-credential-mappingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "default-credential-mapping-serviceType", propOrder = {
    "x509CredentialMapping"
})
public class DefaultCredentialMappingServiceType {

    @XmlElement(name = "x509-credential-mapping", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected X509CredentialMappingType x509CredentialMapping;

    /**
     * Gets the value of the x509CredentialMapping property.
     * 
     * @return
     *     possible object is
     *     {@link X509CredentialMappingType }
     *     
     */
    public X509CredentialMappingType getX509CredentialMapping() {
        return x509CredentialMapping;
    }

    /**
     * Sets the value of the x509CredentialMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link X509CredentialMappingType }
     *     
     */
    public void setX509CredentialMapping(X509CredentialMappingType value) {
        this.x509CredentialMapping = value;
    }

}
