//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 02:39:44 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for default-identity-assertionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="default-identity-assertionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="x509-identity-assertion" type="{http://www.tmaxsoft.com/xml/ns/jeus}x509-identity-assertionType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "default-identity-assertionType", propOrder = {
    "x509IdentityAssertion"
})
public class DefaultIdentityAssertionType {

    @XmlElement(name = "x509-identity-assertion", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected X509IdentityAssertionType x509IdentityAssertion;

    /**
     * Gets the value of the x509IdentityAssertion property.
     * 
     * @return
     *     possible object is
     *     {@link X509IdentityAssertionType }
     *     
     */
    public X509IdentityAssertionType getX509IdentityAssertion() {
        return x509IdentityAssertion;
    }

    /**
     * Sets the value of the x509IdentityAssertion property.
     * 
     * @param value
     *     allowed object is
     *     {@link X509IdentityAssertionType }
     *     
     */
    public void setX509IdentityAssertion(X509IdentityAssertionType value) {
        this.x509IdentityAssertion = value;
    }

}
