//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 02:39:44 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enable-interopType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enable-interopType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="use-OTS" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="interop-ssl-config" type="{http://www.tmaxsoft.com/xml/ns/jeus}keystore-configType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enable-interopType", propOrder = {
    "useOTS",
    "interopSslConfig"
})
public class EnableInteropType {

    @XmlElement(name = "use-OTS", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "false")
    protected Boolean useOTS;
    @XmlElement(name = "interop-ssl-config", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected KeystoreConfigType interopSslConfig;

    /**
     * Gets the value of the useOTS property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseOTS() {
        return useOTS;
    }

    /**
     * Sets the value of the useOTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseOTS(Boolean value) {
        this.useOTS = value;
    }

    /**
     * Gets the value of the interopSslConfig property.
     * 
     * @return
     *     possible object is
     *     {@link KeystoreConfigType }
     *     
     */
    public KeystoreConfigType getInteropSslConfig() {
        return interopSslConfig;
    }

    /**
     * Sets the value of the interopSslConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeystoreConfigType }
     *     
     */
    public void setInteropSslConfig(KeystoreConfigType value) {
        this.interopSslConfig = value;
    }

}
