//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 02:39:44 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v5_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jeusmain-session-serverType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jeusmain-session-serverType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resolution" type="{http://www.tmaxsoft.com/xml/ns/jeus}nonNegativeIntType" minOccurs="0"/>
 *         &lt;element name="thread-pool" type="{http://www.tmaxsoft.com/xml/ns/jeus}poolingType" minOccurs="0"/>
 *         &lt;element name="use-nio" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="connect-timeout" type="{http://www.tmaxsoft.com/xml/ns/jeus}nonNegativeLongType" minOccurs="0"/>
 *         &lt;element name="read-timeout" type="{http://www.tmaxsoft.com/xml/ns/jeus}nonNegativeLongType" minOccurs="0"/>
 *         &lt;element name="session-manager" type="{http://www.tmaxsoft.com/xml/ns/jeus}session-managerType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jeusmain-session-serverType", propOrder = {
    "resolution",
    "threadPool",
    "useNio",
    "connectTimeout",
    "readTimeout",
    "sessionManager"
})
public class JeusmainSessionServerType {

    @XmlElement(namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "60000")
    protected Integer resolution;
    @XmlElement(name = "thread-pool", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected PoolingType threadPool;
    @XmlElement(name = "use-nio", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "true")
    protected Boolean useNio;
    @XmlElement(name = "connect-timeout", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "5000")
    protected Long connectTimeout;
    @XmlElement(name = "read-timeout", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "20000")
    protected Long readTimeout;
    @XmlElement(name = "session-manager", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", required = true)
    protected List<SessionManagerType> sessionManager;

    /**
     * Gets the value of the resolution property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResolution(Integer value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the threadPool property.
     * 
     * @return
     *     possible object is
     *     {@link PoolingType }
     *     
     */
    public PoolingType getThreadPool() {
        return threadPool;
    }

    /**
     * Sets the value of the threadPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoolingType }
     *     
     */
    public void setThreadPool(PoolingType value) {
        this.threadPool = value;
    }

    /**
     * Gets the value of the useNio property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseNio() {
        return useNio;
    }

    /**
     * Sets the value of the useNio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseNio(Boolean value) {
        this.useNio = value;
    }

    /**
     * Gets the value of the connectTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConnectTimeout() {
        return connectTimeout;
    }

    /**
     * Sets the value of the connectTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConnectTimeout(Long value) {
        this.connectTimeout = value;
    }

    /**
     * Gets the value of the readTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReadTimeout() {
        return readTimeout;
    }

    /**
     * Sets the value of the readTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReadTimeout(Long value) {
        this.readTimeout = value;
    }

    /**
     * Gets the value of the sessionManager property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sessionManager property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSessionManager().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SessionManagerType }
     * 
     * 
     */
    public List<SessionManagerType> getSessionManager() {
        if (sessionManager == null) {
            sessionManager = new ArrayList<SessionManagerType>();
        }
        return this.sessionManager;
    }

}
