//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 02:39:44 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.application.jeus.v5_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jmx-connectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jmx-connectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jmxmp-connector" type="{http://www.tmaxsoft.com/xml/ns/jeus}jmxmp-connectorType" minOccurs="0"/>
 *         &lt;element name="rmi-connector" type="{http://www.tmaxsoft.com/xml/ns/jeus}rmi-connectorType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jmx-connectorType", propOrder = {
    "jmxmpConnector",
    "rmiConnector"
})
public class JmxConnectorType {

    @XmlElement(name = "jmxmp-connector", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected JmxmpConnectorType jmxmpConnector;
    @XmlElement(name = "rmi-connector", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected RmiConnectorType rmiConnector;

    /**
     * Gets the value of the jmxmpConnector property.
     * 
     * @return
     *     possible object is
     *     {@link JmxmpConnectorType }
     *     
     */
    public JmxmpConnectorType getJmxmpConnector() {
        return jmxmpConnector;
    }

    /**
     * Sets the value of the jmxmpConnector property.
     * 
     * @param value
     *     allowed object is
     *     {@link JmxmpConnectorType }
     *     
     */
    public void setJmxmpConnector(JmxmpConnectorType value) {
        this.jmxmpConnector = value;
    }

    /**
     * Gets the value of the rmiConnector property.
     * 
     * @return
     *     possible object is
     *     {@link RmiConnectorType }
     *     
     */
    public RmiConnectorType getRmiConnector() {
        return rmiConnector;
    }

    /**
     * Sets the value of the rmiConnector property.
     * 
     * @param value
     *     allowed object is
     *     {@link RmiConnectorType }
     *     
     */
    public void setRmiConnector(RmiConnectorType value) {
        this.rmiConnector = value;
    }

}
