//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:32:21 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.jeusejbdd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for db-vendorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="db-vendorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="oracle"/>
 *     &lt;enumeration value="informix"/>
 *     &lt;enumeration value="db2"/>
 *     &lt;enumeration value="mssql"/>
 *     &lt;enumeration value="sybase"/>
 *     &lt;enumeration value="hsql"/>
 *     &lt;enumeration value="cloudscape"/>
 *     &lt;enumeration value="mysql"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "db-vendorType")
@XmlEnum
public enum DbVendorType {


    /**
     * 
     *                         [Description]: Oracle DBMS 인 경우
     *                     
     * 
     */
    @XmlEnumValue("oracle")
    ORACLE("oracle"),

    /**
     * 
     *                         [Description]: Informix DBMS 인 경우
     *                     
     * 
     */
    @XmlEnumValue("informix")
    INFORMIX("informix"),

    /**
     * 
     *                         [Description]: IBM DB2 DBMS인 경우
     *                     
     * 
     */
    @XmlEnumValue("db2")
    DB_2("db2"),

    /**
     * 
     *                         [Description]: Microsoft SQL Server DBMS 인 경우
     *                     
     * 
     */
    @XmlEnumValue("mssql")
    MSSQL("mssql"),

    /**
     * 
     *                         [Description]: Sybase DBMS인 경우
     *                     
     * 
     */
    @XmlEnumValue("sybase")
    SYBASE("sybase"),

    /**
     * 
     *                         [Description]: HSQL DBMS 인 경우
     *                     
     * 
     */
    @XmlEnumValue("hsql")
    HSQL("hsql"),

    /**
     * 
     *                         [Description]: Cloudscape DBMS인 경우
     *                     
     * 
     */
    @XmlEnumValue("cloudscape")
    CLOUDSCAPE("cloudscape"),

    /**
     * 
     *                         [Description]: MySQL DBMS인 경우
     *                     
     * 
     */
    @XmlEnumValue("mysql")
    MYSQL("mysql");
    private final String value;

    DbVendorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DbVendorType fromValue(String v) {
        for (DbVendorType c: DbVendorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
