//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:32:21 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.jeusejbdd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for jeus-beanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jeus-beanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ejb-name" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="export-name" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="local-export-name" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="export-port" type="{http://www.tmaxsoft.com/xml/ns/jeus}nonNegativeIntType" minOccurs="0"/>
 *         &lt;element name="export-iiop" type="{http://www.tmaxsoft.com/xml/ns/jeus}export-iiopType" minOccurs="0"/>
 *         &lt;element name="single-vm-only" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="local-invoke-optimize" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="use-access-control" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="run-as-identity" type="{http://www.tmaxsoft.com/xml/ns/jeus}run-as-identityType" minOccurs="0"/>
 *         &lt;element name="security-interop" type="{http://www.tmaxsoft.com/xml/ns/jeus}security-interopType" minOccurs="0"/>
 *         &lt;element name="env" type="{http://www.tmaxsoft.com/xml/ns/jeus}envType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ejb-ref" type="{http://www.tmaxsoft.com/xml/ns/jeus}jndi-refType" minOccurs="0"/>
 *         &lt;element name="res-ref" type="{http://www.tmaxsoft.com/xml/ns/jeus}jndi-refType" minOccurs="0"/>
 *         &lt;element name="res-env-ref" type="{http://www.tmaxsoft.com/xml/ns/jeus}jndi-refType" minOccurs="0"/>
 *         &lt;element name="service-ref" type="{http://www.tmaxsoft.com/xml/ns/jeus}jeus-webservices-client-ddType" minOccurs="0"/>
 *         &lt;element name="thread-max" type="{http://www.tmaxsoft.com/xml/ns/jeus}nonNegativeIntType" minOccurs="0"/>
 *         &lt;element name="clustering" type="{http://www.tmaxsoft.com/xml/ns/jeus}clusteringType" minOccurs="0"/>
 *         &lt;element name="invoke-http" type="{http://www.tmaxsoft.com/xml/ns/jeus}invoke-httpType" minOccurs="0"/>
 *         &lt;element name="pooling-bean" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="object-management" type="{http://www.tmaxsoft.com/xml/ns/jeus}object-managementType" minOccurs="0"/>
 *         &lt;element name="file-db-info" type="{http://www.tmaxsoft.com/xml/ns/jeus}file-db-infoType" minOccurs="0"/>
 *         &lt;element name="persistence-optimize" type="{http://www.tmaxsoft.com/xml/ns/jeus}persistence-optimizeType" minOccurs="0"/>
 *         &lt;element name="schema-info" type="{http://www.tmaxsoft.com/xml/ns/jeus}schema-infoType" minOccurs="0"/>
 *         &lt;element name="database-insert-delay" type="{http://www.tmaxsoft.com/xml/ns/jeus}database-insert-delayType" minOccurs="0"/>
 *         &lt;element name="cm-persistence-optimize" type="{http://www.tmaxsoft.com/xml/ns/jeus}cm-persistence-optimizeType" minOccurs="0"/>
 *         &lt;element name="enable-instant-ql" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="connection-factory-name" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="mdb-resource-adapter" type="{http://www.tmaxsoft.com/xml/ns/jeus}mdb-resource-adapterType" minOccurs="0"/>
 *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="max-message" type="{http://www.tmaxsoft.com/xml/ns/jeus}nonNegativeIntType" minOccurs="0"/>
 *         &lt;element name="ack-mode" type="{http://www.tmaxsoft.com/xml/ns/jeus}ack-modeType" minOccurs="0"/>
 *         &lt;element name="durable" type="{http://www.tmaxsoft.com/xml/ns/jeus}durableType" minOccurs="0"/>
 *         &lt;element name="msg-selector" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="jndi-spi" type="{http://www.tmaxsoft.com/xml/ns/jeus}jndi-spiType" minOccurs="0"/>
 *         &lt;element name="durable-timer-service" type="{http://www.tmaxsoft.com/xml/ns/jeus}durable-timer-serviceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jeus-beanType", propOrder = {
    "ejbName",
    "exportName",
    "localExportName",
    "exportPort",
    "exportIiop",
    "singleVmOnly",
    "localInvokeOptimize",
    "useAccessControl",
    "runAsIdentity",
    "securityInterop",
    "env",
    "ejbRef",
    "resRef",
    "resEnvRef",
    "serviceRef",
    "threadMax",
    "clustering",
    "invokeHttp",
    "poolingBean",
    "objectManagement",
    "fileDbInfo",
    "persistenceOptimize",
    "schemaInfo",
    "databaseInsertDelay",
    "cmPersistenceOptimize",
    "enableInstantQl",
    "connectionFactoryName",
    "mdbResourceAdapter",
    "destination",
    "maxMessage",
    "ackMode",
    "durable",
    "msgSelector",
    "jndiSpi",
    "durableTimerService"
})
public class JeusBeanType {

    @XmlElement(name = "ejb-name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String ejbName;
    @XmlElement(name = "export-name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String exportName;
    @XmlElement(name = "local-export-name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String localExportName;
    @XmlElement(name = "export-port", defaultValue = "0")
    protected Integer exportPort;
    @XmlElement(name = "export-iiop")
    protected ExportIiopType exportIiop;
    @XmlElement(name = "single-vm-only", defaultValue = "false")
    protected Boolean singleVmOnly;
    @XmlElement(name = "local-invoke-optimize", defaultValue = "true")
    protected Boolean localInvokeOptimize;
    @XmlElement(name = "use-access-control", defaultValue = "false")
    protected Boolean useAccessControl;
    @XmlElement(name = "run-as-identity")
    protected RunAsIdentityType runAsIdentity;
    @XmlElement(name = "security-interop")
    protected SecurityInteropType securityInterop;
    protected List<EnvType> env;
    @XmlElement(name = "ejb-ref")
    protected JndiRefType ejbRef;
    @XmlElement(name = "res-ref")
    protected JndiRefType resRef;
    @XmlElement(name = "res-env-ref")
    protected JndiRefType resEnvRef;
    @XmlElement(name = "service-ref")
    protected JeusWebservicesClientDdType serviceRef;
    @XmlElement(name = "thread-max", defaultValue = "100")
    protected Integer threadMax;
    protected ClusteringType clustering;
    @XmlElement(name = "invoke-http")
    protected InvokeHttpType invokeHttp;
    @XmlElement(name = "pooling-bean", defaultValue = "false")
    protected Boolean poolingBean;
    @XmlElement(name = "object-management")
    protected ObjectManagementType objectManagement;
    @XmlElement(name = "file-db-info")
    protected FileDbInfoType fileDbInfo;
    @XmlElement(name = "persistence-optimize")
    protected PersistenceOptimizeType persistenceOptimize;
    @XmlElement(name = "schema-info")
    protected SchemaInfoType schemaInfo;
    @XmlElement(name = "database-insert-delay", defaultValue = "ejbPostCreate")
    protected DatabaseInsertDelayType databaseInsertDelay;
    @XmlElement(name = "cm-persistence-optimize")
    protected CmPersistenceOptimizeType cmPersistenceOptimize;
    @XmlElement(name = "enable-instant-ql", defaultValue = "false")
    protected Boolean enableInstantQl;
    @XmlElement(name = "connection-factory-name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String connectionFactoryName;
    @XmlElement(name = "mdb-resource-adapter")
    protected MdbResourceAdapterType mdbResourceAdapter;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String destination;
    @XmlElement(name = "max-message", defaultValue = "10")
    protected Integer maxMessage;
    @XmlElement(name = "ack-mode")
    protected AckModeType ackMode;
    protected DurableType durable;
    @XmlElement(name = "msg-selector")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String msgSelector;
    @XmlElement(name = "jndi-spi")
    protected JndiSpiType jndiSpi;
    @XmlElement(name = "durable-timer-service")
    protected DurableTimerServiceType durableTimerService;

    /**
     * Gets the value of the ejbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjbName() {
        return ejbName;
    }

    /**
     * Sets the value of the ejbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjbName(String value) {
        this.ejbName = value;
    }

    /**
     * Gets the value of the exportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportName() {
        return exportName;
    }

    /**
     * Sets the value of the exportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportName(String value) {
        this.exportName = value;
    }

    /**
     * Gets the value of the localExportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalExportName() {
        return localExportName;
    }

    /**
     * Sets the value of the localExportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalExportName(String value) {
        this.localExportName = value;
    }

    /**
     * Gets the value of the exportPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExportPort() {
        return exportPort;
    }

    /**
     * Sets the value of the exportPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExportPort(Integer value) {
        this.exportPort = value;
    }

    /**
     * Gets the value of the exportIiop property.
     * 
     * @return
     *     possible object is
     *     {@link ExportIiopType }
     *     
     */
    public ExportIiopType getExportIiop() {
        return exportIiop;
    }

    /**
     * Sets the value of the exportIiop property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportIiopType }
     *     
     */
    public void setExportIiop(ExportIiopType value) {
        this.exportIiop = value;
    }

    /**
     * Gets the value of the singleVmOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSingleVmOnly() {
        return singleVmOnly;
    }

    /**
     * Sets the value of the singleVmOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingleVmOnly(Boolean value) {
        this.singleVmOnly = value;
    }

    /**
     * Gets the value of the localInvokeOptimize property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocalInvokeOptimize() {
        return localInvokeOptimize;
    }

    /**
     * Sets the value of the localInvokeOptimize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalInvokeOptimize(Boolean value) {
        this.localInvokeOptimize = value;
    }

    /**
     * Gets the value of the useAccessControl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseAccessControl() {
        return useAccessControl;
    }

    /**
     * Sets the value of the useAccessControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseAccessControl(Boolean value) {
        this.useAccessControl = value;
    }

    /**
     * Gets the value of the runAsIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link RunAsIdentityType }
     *     
     */
    public RunAsIdentityType getRunAsIdentity() {
        return runAsIdentity;
    }

    /**
     * Sets the value of the runAsIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunAsIdentityType }
     *     
     */
    public void setRunAsIdentity(RunAsIdentityType value) {
        this.runAsIdentity = value;
    }

    /**
     * Gets the value of the securityInterop property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityInteropType }
     *     
     */
    public SecurityInteropType getSecurityInterop() {
        return securityInterop;
    }

    /**
     * Sets the value of the securityInterop property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityInteropType }
     *     
     */
    public void setSecurityInterop(SecurityInteropType value) {
        this.securityInterop = value;
    }

    /**
     * Gets the value of the env property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the env property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnv().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnvType }
     * 
     * 
     */
    public List<EnvType> getEnv() {
        if (env == null) {
            env = new ArrayList<EnvType>();
        }
        return this.env;
    }

    /**
     * Gets the value of the ejbRef property.
     * 
     * @return
     *     possible object is
     *     {@link JndiRefType }
     *     
     */
    public JndiRefType getEjbRef() {
        return ejbRef;
    }

    /**
     * Sets the value of the ejbRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JndiRefType }
     *     
     */
    public void setEjbRef(JndiRefType value) {
        this.ejbRef = value;
    }

    /**
     * Gets the value of the resRef property.
     * 
     * @return
     *     possible object is
     *     {@link JndiRefType }
     *     
     */
    public JndiRefType getResRef() {
        return resRef;
    }

    /**
     * Sets the value of the resRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JndiRefType }
     *     
     */
    public void setResRef(JndiRefType value) {
        this.resRef = value;
    }

    /**
     * Gets the value of the resEnvRef property.
     * 
     * @return
     *     possible object is
     *     {@link JndiRefType }
     *     
     */
    public JndiRefType getResEnvRef() {
        return resEnvRef;
    }

    /**
     * Sets the value of the resEnvRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JndiRefType }
     *     
     */
    public void setResEnvRef(JndiRefType value) {
        this.resEnvRef = value;
    }

    /**
     * Gets the value of the serviceRef property.
     * 
     * @return
     *     possible object is
     *     {@link JeusWebservicesClientDdType }
     *     
     */
    public JeusWebservicesClientDdType getServiceRef() {
        return serviceRef;
    }

    /**
     * Sets the value of the serviceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JeusWebservicesClientDdType }
     *     
     */
    public void setServiceRef(JeusWebservicesClientDdType value) {
        this.serviceRef = value;
    }

    /**
     * Gets the value of the threadMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThreadMax() {
        return threadMax;
    }

    /**
     * Sets the value of the threadMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThreadMax(Integer value) {
        this.threadMax = value;
    }

    /**
     * Gets the value of the clustering property.
     * 
     * @return
     *     possible object is
     *     {@link ClusteringType }
     *     
     */
    public ClusteringType getClustering() {
        return clustering;
    }

    /**
     * Sets the value of the clustering property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClusteringType }
     *     
     */
    public void setClustering(ClusteringType value) {
        this.clustering = value;
    }

    /**
     * Gets the value of the invokeHttp property.
     * 
     * @return
     *     possible object is
     *     {@link InvokeHttpType }
     *     
     */
    public InvokeHttpType getInvokeHttp() {
        return invokeHttp;
    }

    /**
     * Sets the value of the invokeHttp property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvokeHttpType }
     *     
     */
    public void setInvokeHttp(InvokeHttpType value) {
        this.invokeHttp = value;
    }

    /**
     * Gets the value of the poolingBean property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPoolingBean() {
        return poolingBean;
    }

    /**
     * Sets the value of the poolingBean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPoolingBean(Boolean value) {
        this.poolingBean = value;
    }

    /**
     * Gets the value of the objectManagement property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectManagementType }
     *     
     */
    public ObjectManagementType getObjectManagement() {
        return objectManagement;
    }

    /**
     * Sets the value of the objectManagement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectManagementType }
     *     
     */
    public void setObjectManagement(ObjectManagementType value) {
        this.objectManagement = value;
    }

    /**
     * Gets the value of the fileDbInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FileDbInfoType }
     *     
     */
    public FileDbInfoType getFileDbInfo() {
        return fileDbInfo;
    }

    /**
     * Sets the value of the fileDbInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileDbInfoType }
     *     
     */
    public void setFileDbInfo(FileDbInfoType value) {
        this.fileDbInfo = value;
    }

    /**
     * Gets the value of the persistenceOptimize property.
     * 
     * @return
     *     possible object is
     *     {@link PersistenceOptimizeType }
     *     
     */
    public PersistenceOptimizeType getPersistenceOptimize() {
        return persistenceOptimize;
    }

    /**
     * Sets the value of the persistenceOptimize property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersistenceOptimizeType }
     *     
     */
    public void setPersistenceOptimize(PersistenceOptimizeType value) {
        this.persistenceOptimize = value;
    }

    /**
     * Gets the value of the schemaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaInfoType }
     *     
     */
    public SchemaInfoType getSchemaInfo() {
        return schemaInfo;
    }

    /**
     * Sets the value of the schemaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaInfoType }
     *     
     */
    public void setSchemaInfo(SchemaInfoType value) {
        this.schemaInfo = value;
    }

    /**
     * Gets the value of the databaseInsertDelay property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseInsertDelayType }
     *     
     */
    public DatabaseInsertDelayType getDatabaseInsertDelay() {
        return databaseInsertDelay;
    }

    /**
     * Sets the value of the databaseInsertDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseInsertDelayType }
     *     
     */
    public void setDatabaseInsertDelay(DatabaseInsertDelayType value) {
        this.databaseInsertDelay = value;
    }

    /**
     * Gets the value of the cmPersistenceOptimize property.
     * 
     * @return
     *     possible object is
     *     {@link CmPersistenceOptimizeType }
     *     
     */
    public CmPersistenceOptimizeType getCmPersistenceOptimize() {
        return cmPersistenceOptimize;
    }

    /**
     * Sets the value of the cmPersistenceOptimize property.
     * 
     * @param value
     *     allowed object is
     *     {@link CmPersistenceOptimizeType }
     *     
     */
    public void setCmPersistenceOptimize(CmPersistenceOptimizeType value) {
        this.cmPersistenceOptimize = value;
    }

    /**
     * Gets the value of the enableInstantQl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableInstantQl() {
        return enableInstantQl;
    }

    /**
     * Sets the value of the enableInstantQl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableInstantQl(Boolean value) {
        this.enableInstantQl = value;
    }

    /**
     * Gets the value of the connectionFactoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionFactoryName() {
        return connectionFactoryName;
    }

    /**
     * Sets the value of the connectionFactoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionFactoryName(String value) {
        this.connectionFactoryName = value;
    }

    /**
     * Gets the value of the mdbResourceAdapter property.
     * 
     * @return
     *     possible object is
     *     {@link MdbResourceAdapterType }
     *     
     */
    public MdbResourceAdapterType getMdbResourceAdapter() {
        return mdbResourceAdapter;
    }

    /**
     * Sets the value of the mdbResourceAdapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link MdbResourceAdapterType }
     *     
     */
    public void setMdbResourceAdapter(MdbResourceAdapterType value) {
        this.mdbResourceAdapter = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the maxMessage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxMessage() {
        return maxMessage;
    }

    /**
     * Sets the value of the maxMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxMessage(Integer value) {
        this.maxMessage = value;
    }

    /**
     * Gets the value of the ackMode property.
     * 
     * @return
     *     possible object is
     *     {@link AckModeType }
     *     
     */
    public AckModeType getAckMode() {
        return ackMode;
    }

    /**
     * Sets the value of the ackMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckModeType }
     *     
     */
    public void setAckMode(AckModeType value) {
        this.ackMode = value;
    }

    /**
     * Gets the value of the durable property.
     * 
     * @return
     *     possible object is
     *     {@link DurableType }
     *     
     */
    public DurableType getDurable() {
        return durable;
    }

    /**
     * Sets the value of the durable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurableType }
     *     
     */
    public void setDurable(DurableType value) {
        this.durable = value;
    }

    /**
     * Gets the value of the msgSelector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgSelector() {
        return msgSelector;
    }

    /**
     * Sets the value of the msgSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgSelector(String value) {
        this.msgSelector = value;
    }

    /**
     * Gets the value of the jndiSpi property.
     * 
     * @return
     *     possible object is
     *     {@link JndiSpiType }
     *     
     */
    public JndiSpiType getJndiSpi() {
        return jndiSpi;
    }

    /**
     * Sets the value of the jndiSpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JndiSpiType }
     *     
     */
    public void setJndiSpi(JndiSpiType value) {
        this.jndiSpi = value;
    }

    /**
     * Gets the value of the durableTimerService property.
     * 
     * @return
     *     possible object is
     *     {@link DurableTimerServiceType }
     *     
     */
    public DurableTimerServiceType getDurableTimerService() {
        return durableTimerService;
    }

    /**
     * Sets the value of the durableTimerService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurableTimerServiceType }
     *     
     */
    public void setDurableTimerService(DurableTimerServiceType value) {
        this.durableTimerService = value;
    }

}
