//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 12:32:21 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.jeusejbdd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for signature-infoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="signature-infoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="signatureParts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signatureAlgorithm" type="{http://www.tmaxsoft.com/xml/ns/jeus}signatureAlgorithmType" minOccurs="0"/>
 *         &lt;element name="messageDigestAlogrithm" type="{http://www.tmaxsoft.com/xml/ns/jeus}messageDigestAlgorithmType" minOccurs="0"/>
 *         &lt;element name="canonicalization" type="{http://www.tmaxsoft.com/xml/ns/jeus}canonicalizationType" minOccurs="0"/>
 *         &lt;element name="keyIdentifier" type="{http://www.tmaxsoft.com/xml/ns/jeus}sigKeyIdentifierType"/>
 *         &lt;element name="keystore" type="{http://www.tmaxsoft.com/xml/ns/jeus}keystoreType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signature-infoType", propOrder = {
    "signatureParts",
    "signatureAlgorithm",
    "messageDigestAlogrithm",
    "canonicalization",
    "keyIdentifier",
    "keystore"
})
public class SignatureInfoType {

    protected String signatureParts;
    protected SignatureAlgorithmType signatureAlgorithm;
    protected MessageDigestAlgorithmType messageDigestAlogrithm;
    protected CanonicalizationType canonicalization;
    @XmlElement(required = true)
    protected SigKeyIdentifierType keyIdentifier;
    protected KeystoreType keystore;

    /**
     * Gets the value of the signatureParts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureParts() {
        return signatureParts;
    }

    /**
     * Sets the value of the signatureParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureParts(String value) {
        this.signatureParts = value;
    }

    /**
     * Gets the value of the signatureAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureAlgorithmType }
     *     
     */
    public SignatureAlgorithmType getSignatureAlgorithm() {
        return signatureAlgorithm;
    }

    /**
     * Sets the value of the signatureAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureAlgorithmType }
     *     
     */
    public void setSignatureAlgorithm(SignatureAlgorithmType value) {
        this.signatureAlgorithm = value;
    }

    /**
     * Gets the value of the messageDigestAlogrithm property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDigestAlgorithmType }
     *     
     */
    public MessageDigestAlgorithmType getMessageDigestAlogrithm() {
        return messageDigestAlogrithm;
    }

    /**
     * Sets the value of the messageDigestAlogrithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDigestAlgorithmType }
     *     
     */
    public void setMessageDigestAlogrithm(MessageDigestAlgorithmType value) {
        this.messageDigestAlogrithm = value;
    }

    /**
     * Gets the value of the canonicalization property.
     * 
     * @return
     *     possible object is
     *     {@link CanonicalizationType }
     *     
     */
    public CanonicalizationType getCanonicalization() {
        return canonicalization;
    }

    /**
     * Sets the value of the canonicalization property.
     * 
     * @param value
     *     allowed object is
     *     {@link CanonicalizationType }
     *     
     */
    public void setCanonicalization(CanonicalizationType value) {
        this.canonicalization = value;
    }

    /**
     * Gets the value of the keyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link SigKeyIdentifierType }
     *     
     */
    public SigKeyIdentifierType getKeyIdentifier() {
        return keyIdentifier;
    }

    /**
     * Sets the value of the keyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SigKeyIdentifierType }
     *     
     */
    public void setKeyIdentifier(SigKeyIdentifierType value) {
        this.keyIdentifier = value;
    }

    /**
     * Gets the value of the keystore property.
     * 
     * @return
     *     possible object is
     *     {@link KeystoreType }
     *     
     */
    public KeystoreType getKeystore() {
        return keystore;
    }

    /**
     * Sets the value of the keystore property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeystoreType }
     *     
     */
    public void setKeystore(KeystoreType value) {
        this.keystore = value;
    }

}
