//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.06 at 09:23:00 오후 KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bea.com/ns/weblogic/90")
package com.athena.chameleon.engine.entity.xml.ejbjar.weblogic.v9_0;
