//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.06 at 09:23:00 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.ejbjar.weblogic.v9_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for weblogic-ejb-jarType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="weblogic-ejb-jarType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/j2ee}descriptionType" minOccurs="0"/>
 *         &lt;element name="weblogic-enterprise-bean" type="{http://www.bea.com/ns/weblogic/90}weblogic-enterprise-beanType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="security-role-assignment" type="{http://www.bea.com/ns/weblogic/90}security-role-assignmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="run-as-role-assignment" type="{http://www.bea.com/ns/weblogic/90}run-as-role-assignmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="security-permission" type="{http://www.bea.com/ns/weblogic/90}security-permissionType" minOccurs="0"/>
 *         &lt;element name="transaction-isolation" type="{http://www.bea.com/ns/weblogic/90}transaction-isolationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="message-destination-descriptor" type="{http://www.bea.com/ns/weblogic/90}message-destination-descriptorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="idempotent-methods" type="{http://www.bea.com/ns/weblogic/90}idempotent-methodsType" minOccurs="0"/>
 *         &lt;element name="retry-methods-on-rollback" type="{http://www.bea.com/ns/weblogic/90}retry-methods-on-rollbackType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="enable-bean-class-redeploy" type="{http://www.bea.com/ns/weblogic/90}true-falseType" minOccurs="0"/>
 *         &lt;element name="disable-warning" type="{http://www.bea.com/ns/weblogic/90}disable-warningType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="work-manager" type="{http://www.bea.com/ns/weblogic/90}work-managerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="weblogic-compatibility" type="{http://www.bea.com/ns/weblogic/90}weblogic-compatibilityType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "weblogic-ejb-jarType", propOrder = {
    "description",
    "weblogicEnterpriseBean",
    "securityRoleAssignment",
    "runAsRoleAssignment",
    "securityPermission",
    "transactionIsolation",
    "messageDestinationDescriptor",
    "idempotentMethods",
    "retryMethodsOnRollback",
    "enableBeanClassRedeploy",
    "disableWarning",
    "workManager",
    "weblogicCompatibility"
})
public class WeblogicEjbJarType {

    @XmlElement(namespace = "http://www.bea.com/ns/weblogic/90")
    protected DescriptionType description;
    @XmlElement(name = "weblogic-enterprise-bean", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<WeblogicEnterpriseBeanType> weblogicEnterpriseBean;
    @XmlElement(name = "security-role-assignment", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<SecurityRoleAssignmentType> securityRoleAssignment;
    @XmlElement(name = "run-as-role-assignment", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<RunAsRoleAssignmentType> runAsRoleAssignment;
    @XmlElement(name = "security-permission", namespace = "http://www.bea.com/ns/weblogic/90")
    protected SecurityPermissionType securityPermission;
    @XmlElement(name = "transaction-isolation", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<TransactionIsolationType> transactionIsolation;
    @XmlElement(name = "message-destination-descriptor", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<MessageDestinationDescriptorType> messageDestinationDescriptor;
    @XmlElement(name = "idempotent-methods", namespace = "http://www.bea.com/ns/weblogic/90")
    protected IdempotentMethodsType idempotentMethods;
    @XmlElement(name = "retry-methods-on-rollback", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<RetryMethodsOnRollbackType> retryMethodsOnRollback;
    @XmlElement(name = "enable-bean-class-redeploy", namespace = "http://www.bea.com/ns/weblogic/90")
    protected TrueFalseType enableBeanClassRedeploy;
    @XmlElement(name = "disable-warning", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<DisableWarningType> disableWarning;
    @XmlElement(name = "work-manager", namespace = "http://www.bea.com/ns/weblogic/90", required = true)
    protected List<WorkManagerType> workManager;
    @XmlElement(name = "weblogic-compatibility", namespace = "http://www.bea.com/ns/weblogic/90")
    protected WeblogicCompatibilityType weblogicCompatibility;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected java.lang.String id;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setDescription(DescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the weblogicEnterpriseBean property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the weblogicEnterpriseBean property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWeblogicEnterpriseBean().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WeblogicEnterpriseBeanType }
     * 
     * 
     */
    public List<WeblogicEnterpriseBeanType> getWeblogicEnterpriseBean() {
        if (weblogicEnterpriseBean == null) {
            weblogicEnterpriseBean = new ArrayList<WeblogicEnterpriseBeanType>();
        }
        return this.weblogicEnterpriseBean;
    }

    /**
     * Gets the value of the securityRoleAssignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityRoleAssignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityRoleAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityRoleAssignmentType }
     * 
     * 
     */
    public List<SecurityRoleAssignmentType> getSecurityRoleAssignment() {
        if (securityRoleAssignment == null) {
            securityRoleAssignment = new ArrayList<SecurityRoleAssignmentType>();
        }
        return this.securityRoleAssignment;
    }

    /**
     * Gets the value of the runAsRoleAssignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runAsRoleAssignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRunAsRoleAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RunAsRoleAssignmentType }
     * 
     * 
     */
    public List<RunAsRoleAssignmentType> getRunAsRoleAssignment() {
        if (runAsRoleAssignment == null) {
            runAsRoleAssignment = new ArrayList<RunAsRoleAssignmentType>();
        }
        return this.runAsRoleAssignment;
    }

    /**
     * Gets the value of the securityPermission property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityPermissionType }
     *     
     */
    public SecurityPermissionType getSecurityPermission() {
        return securityPermission;
    }

    /**
     * Sets the value of the securityPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityPermissionType }
     *     
     */
    public void setSecurityPermission(SecurityPermissionType value) {
        this.securityPermission = value;
    }

    /**
     * Gets the value of the transactionIsolation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transactionIsolation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransactionIsolation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionIsolationType }
     * 
     * 
     */
    public List<TransactionIsolationType> getTransactionIsolation() {
        if (transactionIsolation == null) {
            transactionIsolation = new ArrayList<TransactionIsolationType>();
        }
        return this.transactionIsolation;
    }

    /**
     * Gets the value of the messageDestinationDescriptor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageDestinationDescriptor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageDestinationDescriptor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageDestinationDescriptorType }
     * 
     * 
     */
    public List<MessageDestinationDescriptorType> getMessageDestinationDescriptor() {
        if (messageDestinationDescriptor == null) {
            messageDestinationDescriptor = new ArrayList<MessageDestinationDescriptorType>();
        }
        return this.messageDestinationDescriptor;
    }

    /**
     * Gets the value of the idempotentMethods property.
     * 
     * @return
     *     possible object is
     *     {@link IdempotentMethodsType }
     *     
     */
    public IdempotentMethodsType getIdempotentMethods() {
        return idempotentMethods;
    }

    /**
     * Sets the value of the idempotentMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdempotentMethodsType }
     *     
     */
    public void setIdempotentMethods(IdempotentMethodsType value) {
        this.idempotentMethods = value;
    }

    /**
     * Gets the value of the retryMethodsOnRollback property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retryMethodsOnRollback property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetryMethodsOnRollback().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetryMethodsOnRollbackType }
     * 
     * 
     */
    public List<RetryMethodsOnRollbackType> getRetryMethodsOnRollback() {
        if (retryMethodsOnRollback == null) {
            retryMethodsOnRollback = new ArrayList<RetryMethodsOnRollbackType>();
        }
        return this.retryMethodsOnRollback;
    }

    /**
     * Gets the value of the enableBeanClassRedeploy property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getEnableBeanClassRedeploy() {
        return enableBeanClassRedeploy;
    }

    /**
     * Sets the value of the enableBeanClassRedeploy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setEnableBeanClassRedeploy(TrueFalseType value) {
        this.enableBeanClassRedeploy = value;
    }

    /**
     * Gets the value of the disableWarning property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disableWarning property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisableWarning().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisableWarningType }
     * 
     * 
     */
    public List<DisableWarningType> getDisableWarning() {
        if (disableWarning == null) {
            disableWarning = new ArrayList<DisableWarningType>();
        }
        return this.disableWarning;
    }

    /**
     * Gets the value of the workManager property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workManager property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkManager().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkManagerType }
     * 
     * 
     */
    public List<WorkManagerType> getWorkManager() {
        if (workManager == null) {
            workManager = new ArrayList<WorkManagerType>();
        }
        return this.workManager;
    }

    /**
     * Gets the value of the weblogicCompatibility property.
     * 
     * @return
     *     possible object is
     *     {@link WeblogicCompatibilityType }
     *     
     */
    public WeblogicCompatibilityType getWeblogicCompatibility() {
        return weblogicCompatibility;
    }

    /**
     * Sets the value of the weblogicCompatibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeblogicCompatibilityType }
     *     
     */
    public void setWeblogicCompatibility(WeblogicCompatibilityType value) {
        this.weblogicCompatibility = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
