//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 10:14:54 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.jeusejbdd.v6_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ejb-module-infoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ejb-module-infoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ejb11-compatible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="keep-generated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="fast-deploy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="role-permission" type="{http://www.tmaxsoft.com/xml/ns/jeus}rolePermissionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="unspecified-method-permission" type="{http://www.tmaxsoft.com/xml/ns/jeus}unspecified-method-permissionType" minOccurs="0"/>
 *         &lt;element name="unspecified-container-transaction" type="{http://www.tmaxsoft.com/xml/ns/jeus}trans-attributeType" minOccurs="0"/>
 *         &lt;element name="latest-client" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="use-dynamic-proxy-for-ejb2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ejb-module-infoType", propOrder = {
    "ejb11Compatible",
    "keepGenerated",
    "fastDeploy",
    "rolePermission",
    "unspecifiedMethodPermission",
    "unspecifiedContainerTransaction",
    "latestClient",
    "useDynamicProxyForEjb2"
})
public class EjbModuleInfoType {

    @XmlElement(name = "ejb11-compatible", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "false")
    protected Boolean ejb11Compatible;
    @XmlElement(name = "keep-generated", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "false")
    protected Boolean keepGenerated;
    @XmlElement(name = "fast-deploy", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "false")
    protected Boolean fastDeploy;
    @XmlElement(name = "role-permission", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", required = true)
    protected List<RolePermissionType> rolePermission;
    @XmlElement(name = "unspecified-method-permission", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected UnspecifiedMethodPermissionType unspecifiedMethodPermission;
    @XmlElement(name = "unspecified-container-transaction", namespace = "http://www.tmaxsoft.com/xml/ns/jeus")
    protected TransAttributeType unspecifiedContainerTransaction;
    @XmlElement(name = "latest-client", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "false")
    protected Boolean latestClient;
    @XmlElement(name = "use-dynamic-proxy-for-ejb2", namespace = "http://www.tmaxsoft.com/xml/ns/jeus", defaultValue = "true")
    protected Boolean useDynamicProxyForEjb2;

    /**
     * Gets the value of the ejb11Compatible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEjb11Compatible() {
        return ejb11Compatible;
    }

    /**
     * Sets the value of the ejb11Compatible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEjb11Compatible(Boolean value) {
        this.ejb11Compatible = value;
    }

    /**
     * Gets the value of the keepGenerated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeepGenerated() {
        return keepGenerated;
    }

    /**
     * Sets the value of the keepGenerated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeepGenerated(Boolean value) {
        this.keepGenerated = value;
    }

    /**
     * Gets the value of the fastDeploy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFastDeploy() {
        return fastDeploy;
    }

    /**
     * Sets the value of the fastDeploy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFastDeploy(Boolean value) {
        this.fastDeploy = value;
    }

    /**
     * Gets the value of the rolePermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rolePermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRolePermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RolePermissionType }
     * 
     * 
     */
    public List<RolePermissionType> getRolePermission() {
        if (rolePermission == null) {
            rolePermission = new ArrayList<RolePermissionType>();
        }
        return this.rolePermission;
    }

    /**
     * Gets the value of the unspecifiedMethodPermission property.
     * 
     * @return
     *     possible object is
     *     {@link UnspecifiedMethodPermissionType }
     *     
     */
    public UnspecifiedMethodPermissionType getUnspecifiedMethodPermission() {
        return unspecifiedMethodPermission;
    }

    /**
     * Sets the value of the unspecifiedMethodPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnspecifiedMethodPermissionType }
     *     
     */
    public void setUnspecifiedMethodPermission(UnspecifiedMethodPermissionType value) {
        this.unspecifiedMethodPermission = value;
    }

    /**
     * Gets the value of the unspecifiedContainerTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link TransAttributeType }
     *     
     */
    public TransAttributeType getUnspecifiedContainerTransaction() {
        return unspecifiedContainerTransaction;
    }

    /**
     * Sets the value of the unspecifiedContainerTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransAttributeType }
     *     
     */
    public void setUnspecifiedContainerTransaction(TransAttributeType value) {
        this.unspecifiedContainerTransaction = value;
    }

    /**
     * Gets the value of the latestClient property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLatestClient() {
        return latestClient;
    }

    /**
     * Sets the value of the latestClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLatestClient(Boolean value) {
        this.latestClient = value;
    }

    /**
     * Gets the value of the useDynamicProxyForEjb2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseDynamicProxyForEjb2() {
        return useDynamicProxyForEjb2;
    }

    /**
     * Sets the value of the useDynamicProxyForEjb2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseDynamicProxyForEjb2(Boolean value) {
        this.useDynamicProxyForEjb2 = value;
    }

}
