//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 05:59:07 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.weblogicejbjar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.athena.chameleon.engine.entity.xml.j2ee.XsdNonNegativeIntegerType;
import com.athena.chameleon.engine.entity.xml.j2ee.XsdPositiveIntegerType;


/**
 * <p>Java class for entity-cache-refType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entity-cache-refType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entity-cache-name" type="{http://www.bea.com/ns/weblogic/90}entity-cache-nameType"/>
 *         &lt;element name="idle-timeout-seconds" type="{http://java.sun.com/xml/ns/j2ee}xsdNonNegativeIntegerType" minOccurs="0"/>
 *         &lt;element name="read-timeout-seconds" type="{http://java.sun.com/xml/ns/j2ee}xsdNonNegativeIntegerType" minOccurs="0"/>
 *         &lt;element name="concurrency-strategy" type="{http://www.bea.com/ns/weblogic/90}concurrency-strategyType"/>
 *         &lt;element name="cache-between-transactions" type="{http://www.bea.com/ns/weblogic/90}true-false2Type" minOccurs="0"/>
 *         &lt;element name="estimated-bean-size" type="{http://java.sun.com/xml/ns/j2ee}xsdPositiveIntegerType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entity-cache-refType", propOrder = {
    "entityCacheName",
    "idleTimeoutSeconds",
    "readTimeoutSeconds",
    "concurrencyStrategy",
    "cacheBetweenTransactions",
    "estimatedBeanSize"
})
public class EntityCacheRefType {

    @XmlElement(name = "entity-cache-name", required = true)
    protected EntityCacheNameType entityCacheName;
    @XmlElement(name = "idle-timeout-seconds")
    protected XsdNonNegativeIntegerType idleTimeoutSeconds;
    @XmlElement(name = "read-timeout-seconds")
    protected XsdNonNegativeIntegerType readTimeoutSeconds;
    @XmlElement(name = "concurrency-strategy", required = true)
    protected ConcurrencyStrategyType concurrencyStrategy;
    @XmlElement(name = "cache-between-transactions")
    protected TrueFalseType cacheBetweenTransactions;
    @XmlElement(name = "estimated-bean-size")
    protected XsdPositiveIntegerType estimatedBeanSize;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the entityCacheName property.
     * 
     * @return
     *     possible object is
     *     {@link EntityCacheNameType }
     *     
     */
    public EntityCacheNameType getEntityCacheName() {
        return entityCacheName;
    }

    /**
     * Sets the value of the entityCacheName property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityCacheNameType }
     *     
     */
    public void setEntityCacheName(EntityCacheNameType value) {
        this.entityCacheName = value;
    }

    /**
     * Gets the value of the idleTimeoutSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link XsdNonNegativeIntegerType }
     *     
     */
    public XsdNonNegativeIntegerType getIdleTimeoutSeconds() {
        return idleTimeoutSeconds;
    }

    /**
     * Sets the value of the idleTimeoutSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdNonNegativeIntegerType }
     *     
     */
    public void setIdleTimeoutSeconds(XsdNonNegativeIntegerType value) {
        this.idleTimeoutSeconds = value;
    }

    /**
     * Gets the value of the readTimeoutSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link XsdNonNegativeIntegerType }
     *     
     */
    public XsdNonNegativeIntegerType getReadTimeoutSeconds() {
        return readTimeoutSeconds;
    }

    /**
     * Sets the value of the readTimeoutSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdNonNegativeIntegerType }
     *     
     */
    public void setReadTimeoutSeconds(XsdNonNegativeIntegerType value) {
        this.readTimeoutSeconds = value;
    }

    /**
     * Gets the value of the concurrencyStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link ConcurrencyStrategyType }
     *     
     */
    public ConcurrencyStrategyType getConcurrencyStrategy() {
        return concurrencyStrategy;
    }

    /**
     * Sets the value of the concurrencyStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConcurrencyStrategyType }
     *     
     */
    public void setConcurrencyStrategy(ConcurrencyStrategyType value) {
        this.concurrencyStrategy = value;
    }

    /**
     * Gets the value of the cacheBetweenTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getCacheBetweenTransactions() {
        return cacheBetweenTransactions;
    }

    /**
     * Sets the value of the cacheBetweenTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setCacheBetweenTransactions(TrueFalseType value) {
        this.cacheBetweenTransactions = value;
    }

    /**
     * Gets the value of the estimatedBeanSize property.
     * 
     * @return
     *     possible object is
     *     {@link XsdPositiveIntegerType }
     *     
     */
    public XsdPositiveIntegerType getEstimatedBeanSize() {
        return estimatedBeanSize;
    }

    /**
     * Sets the value of the estimatedBeanSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdPositiveIntegerType }
     *     
     */
    public void setEstimatedBeanSize(XsdPositiveIntegerType value) {
        this.estimatedBeanSize = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
