//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 05:59:07 오후 KST 
//


package com.athena.chameleon.engine.entity.xml.weblogicejbjar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.athena.chameleon.engine.entity.xml.j2ee.RoleNameType;
import com.athena.chameleon.engine.entity.xml.j2ee.XsdNMTOKENType;


/**
 * <p>Java class for run-as-role-assignmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="run-as-role-assignmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="role-name" type="{http://java.sun.com/xml/ns/j2ee}role-nameType"/>
 *         &lt;element name="run-as-principal-name" type="{http://java.sun.com/xml/ns/j2ee}xsdNMTOKENType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "run-as-role-assignmentType", propOrder = {
    "roleName",
    "runAsPrincipalName"
})
public class RunAsRoleAssignmentType {

    @XmlElement(name = "role-name", required = true)
    protected RoleNameType roleName;
    @XmlElement(name = "run-as-principal-name", required = true)
    protected XsdNMTOKENType runAsPrincipalName;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the roleName property.
     * 
     * @return
     *     possible object is
     *     {@link RoleNameType }
     *     
     */
    public RoleNameType getRoleName() {
        return roleName;
    }

    /**
     * Sets the value of the roleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleNameType }
     *     
     */
    public void setRoleName(RoleNameType value) {
        this.roleName = value;
    }

    /**
     * Gets the value of the runAsPrincipalName property.
     * 
     * @return
     *     possible object is
     *     {@link XsdNMTOKENType }
     *     
     */
    public XsdNMTOKENType getRunAsPrincipalName() {
        return runAsPrincipalName;
    }

    /**
     * Sets the value of the runAsPrincipalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdNMTOKENType }
     *     
     */
    public void setRunAsPrincipalName(XsdNMTOKENType value) {
        this.runAsPrincipalName = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
